// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCB8osG9_bM-t7LfsY25NEswF9yeBR970o',
    appId: '1:258126613866:web:2fab93df5550afaa336913',
    messagingSenderId: '258126613866',
    projectId: 'sms-sender-56017',
    authDomain: 'sms-sender-56017.firebaseapp.com',
    storageBucket: 'sms-sender-56017.firebasestorage.app',
    measurementId: 'G-P0K4GQJQRE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChL-HR5DLonH0FGXJ6brkI1-HnTM3fe7w',
    appId: '1:258126613866:android:40be50521be854cc336913',
    messagingSenderId: '258126613866',
    projectId: 'sms-sender-56017',
    storageBucket: 'sms-sender-56017.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgdROvGe67iOxb0qMiLh8BPQABDJJKazE',
    appId: '1:258126613866:ios:2c7e04d0b31efb29336913',
    messagingSenderId: '258126613866',
    projectId: 'sms-sender-56017',
    storageBucket: 'sms-sender-56017.firebasestorage.app',
    iosBundleId: 'com.example.otpSmsSender',
  );
}
